# Generated by Django 3.0.4 on 2020-03-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=160)),
            ],
        ),
    ]
