# Generated by Django 3.0.4 on 2020-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSurname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Content', models.TextField()),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['-publishing_date']},
        ),
    ]
