# Generated by Django 3.0.4 on 2020-03-18 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200318_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
        migrations.AddField(
            model_name='makecomment',
            name='Comments',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.CreatePost'),
            preserve_default=False,
        ),
    ]
