# Generated by Django 3.0.4 on 2020-03-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200318_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makecomment',
            old_name='Comments_id',
            new_name='Comments',
        ),
    ]
